"""Generate pico_firmware_c/verses.h from the public-domain King James Bible.

Downloads book JSON from the aruljohn/Bible-kjv mirror (KJV text, public
domain), selects well-known chapters until the target verse count is reached,
sanitizes everything to uppercase ASCII (the firmware font covers 0x20-0x5F)
and emits a C header with parallel reference/text arrays.

Usage:
    py -3 tools/make_verses.py [--count 1024] [--out pico_firmware_c/verses.h]
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

BASE_URL = "https://raw.githubusercontent.com/aruljohn/Bible-kjv/master/{book}.json"

# (book file name, display name, chapters to include; None = all chapters)
SELECTION = [
    ("Genesis", "GENESIS", [1, 2]),
    ("Exodus", "EXODUS", [20]),
    ("Deuteronomy", "DEUTERONOMY", [6]),
    ("Joshua", "JOSHUA", [1]),
    ("1Samuel", "1 SAMUEL", [17]),
    ("Job", "JOB", [28, 38]),
    ("Psalms", "PSALM", [1, 8, 16, 19, 23, 24, 27, 32, 34, 37, 40, 42, 46,
                          51, 62, 63, 84, 90, 91, 95, 96, 100, 103, 107, 112,
                          116, 118, 121, 127, 130, 133, 138, 139, 143, 145,
                          146, 147, 148, 150]),
    ("Proverbs", "PROVERBS", [1, 2, 3, 4, 10, 15, 16, 22, 31]),
    ("Ecclesiastes", "ECCLESIASTES", [3, 12]),
    ("Isaiah", "ISAIAH", [6, 9, 26, 40, 41, 43, 53, 55, 61]),
    ("Jeremiah", "JEREMIAH", [29]),
    ("Lamentations", "LAMENTATIONS", [3]),
    ("Daniel", "DANIEL", [3]),
    ("Micah", "MICAH", [6]),
    ("Habakkuk", "HABAKKUK", [3]),
    ("Zephaniah", "ZEPHANIAH", [3]),
    ("Matthew", "MATTHEW", [5, 6, 7, 11, 28]),
    ("Mark", "MARK", [12]),
    ("Luke", "LUKE", [2, 15]),
    ("John", "JOHN", [1, 3, 10, 14, 15, 17]),
    ("Acts", "ACTS", [2]),
    ("Romans", "ROMANS", [5, 8, 12]),
    ("1Corinthians", "1 CORINTHIANS", [13, 15]),
    ("2Corinthians", "2 CORINTHIANS", [4, 5]),
    ("Galatians", "GALATIANS", [5]),
    ("Ephesians", "EPHESIANS", [1, 2, 3, 6]),
    ("Philippians", "PHILIPPIANS", [2, 4]),
    ("Colossians", "COLOSSIANS", [3]),
    ("1Thessalonians", "1 THESSALONIANS", [5]),
    ("2Timothy", "2 TIMOTHY", [2]),
    ("Hebrews", "HEBREWS", [11, 12]),
    ("James", "JAMES", [1]),
    ("1Peter", "1 PETER", [1]),
    ("1John", "1 JOHN", [4]),
    ("Revelation", "REVELATION", [21, 22]),
]

REPLACEMENTS = {
    "\u2018": "'", "\u2019": "'", "\u201c": "'", "\u201d": "'",
    "\u2013": "-", "\u2014": "-", "\u00a0": " ",
}


def sanitize(text: str) -> str:
    for src, dst in REPLACEMENTS.items():
        text = text.replace(src, dst)
    text = " ".join(text.split())
    out = []
    for ch in text.upper():
        code = ord(ch)
        if 0x20 <= code <= 0x5F:
            out.append(ch)
    return "".join(out)


def fetch_book(book: str) -> dict:
    with urllib.request.urlopen(BASE_URL.format(book=book), timeout=30) as rsp:
        return json.load(rsp)


def collect(count: int) -> list[tuple[str, str]]:
    verses: list[tuple[str, str]] = []
    for book_file, display, chapters in SELECTION:
        if len(verses) >= count:
            break
        data = fetch_book(book_file)
        by_number = {int(c["chapter"]): c["verses"] for c in data["chapters"]}
        for chapter in chapters:
            if len(verses) >= count:
                break
            for entry in by_number.get(chapter, []):
                if len(verses) >= count:
                    break
                text = sanitize(entry["text"])
                if not text or len(text) > 320:
                    continue
                ref = f"{display} {chapter}:{entry['verse']}"
                verses.append((ref, text))
    return verses


def emit(verses: list[tuple[str, str]], out_path: Path) -> None:
    lines = [
        "// Auto-generated by tools/make_verses.py - do not edit by hand.",
        "// Text: King James Version (public domain).",
        "#ifndef VERSES_H",
        "#define VERSES_H",
        "",
        f"#define VERSE_DB_COUNT {len(verses)}",
        "",
        "static const char *const VERSE_REFS[VERSE_DB_COUNT] = {",
    ]
    for ref, _ in verses:
        lines.append(f'    "{ref}",')
    lines.append("};")
    lines.append("")
    lines.append("static const char *const VERSE_TEXTS[VERSE_DB_COUNT] = {")
    for _, text in verses:
        escaped = text.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",')
    lines.append("};")
    lines.append("")
    lines.append("#endif // VERSES_H")
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=1024)
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent.parent / "pico_firmware_c" / "verses.h"),
    )
    args = parser.parse_args()
    verses = collect(args.count)
    emit(verses, Path(args.out))
    total_bytes = sum(len(r) + len(t) + 2 for r, t in verses)
    print(f"wrote {len(verses)} verses ({total_bytes / 1024:.1f} KiB of text) to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
