"""Generate pico_firmware_c/verses.h from the public-domain King James Bible.

Downloads book JSON from the aruljohn/Bible-kjv mirror (KJV text, public
domain), selects well-known chapters until the target verse count is reached,
sanitizes everything to uppercase ASCII (the firmware font covers 0x20-0x5F)
and emits a C header with parallel reference/text arrays.

Usage:
    py -3 tools/make_verses.py [--count 1024] [--out pico_firmware_c/verses.h]
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

BASE_URL = "https://raw.githubusercontent.com/aruljohn/Bible-kjv/master/{book}.json"

# (book file name, display name, chapters to include; None = all chapters)
# Ordered by priority: the whole New Testament first, then the most-read
# Old Testament books. collect() stops when --count is reached.
SELECTION = [
    ("Matthew", "MATTHEW", None),
    ("Mark", "MARK", None),
    ("Luke", "LUKE", None),
    ("John", "JOHN", None),
    ("Acts", "ACTS", None),
    ("Romans", "ROMANS", None),
    ("1Corinthians", "1 CORINTHIANS", None),
    ("2Corinthians", "2 CORINTHIANS", None),
    ("Galatians", "GALATIANS", None),
    ("Ephesians", "EPHESIANS", None),
    ("Philippians", "PHILIPPIANS", None),
    ("Colossians", "COLOSSIANS", None),
    ("1Thessalonians", "1 THESSALONIANS", None),
    ("2Thessalonians", "2 THESSALONIANS", None),
    ("1Timothy", "1 TIMOTHY", None),
    ("2Timothy", "2 TIMOTHY", None),
    ("Titus", "TITUS", None),
    ("Philemon", "PHILEMON", None),
    ("Hebrews", "HEBREWS", None),
    ("James", "JAMES", None),
    ("1Peter", "1 PETER", None),
    ("2Peter", "2 PETER", None),
    ("1John", "1 JOHN", None),
    ("2John", "2 JOHN", None),
    ("3John", "3 JOHN", None),
    ("Jude", "JUDE", None),
    ("Revelation", "REVELATION", None),
    ("Psalms", "PSALM", None),
    ("Proverbs", "PROVERBS", None),
    ("Genesis", "GENESIS", None),
    ("Ecclesiastes", "ECCLESIASTES", None),
    ("Isaiah", "ISAIAH", None),
    ("Exodus", "EXODUS", None),
    ("Job", "JOB", None),
    ("Daniel", "DANIEL", None),
    ("Joshua", "JOSHUA", None),
    ("Ruth", "RUTH", None),
    ("1Samuel", "1 SAMUEL", None),
    ("2Samuel", "2 SAMUEL", None),
    ("Deuteronomy", "DEUTERONOMY", None),
    ("Jeremiah", "JEREMIAH", None),
    ("Lamentations", "LAMENTATIONS", None),
    ("Ezekiel", "EZEKIEL", None),
    ("Hosea", "HOSEA", None),
    ("Joel", "JOEL", None),
    ("Amos", "AMOS", None),
    ("Obadiah", "OBADIAH", None),
    ("Jonah", "JONAH", None),
    ("Micah", "MICAH", None),
    ("Nahum", "NAHUM", None),
    ("Habakkuk", "HABAKKUK", None),
    ("Zephaniah", "ZEPHANIAH", None),
    ("Haggai", "HAGGAI", None),
    ("Zechariah", "ZECHARIAH", None),
    ("Malachi", "MALACHI", None),
]

REPLACEMENTS = {
    "\u2018": "'", "\u2019": "'", "\u201c": "'", "\u201d": "'",
    "\u2013": "-", "\u2014": "-", "\u00a0": " ",
}


def sanitize(text: str) -> str:
    for src, dst in REPLACEMENTS.items():
        text = text.replace(src, dst)
    text = " ".join(text.split())
    out = []
    for ch in text.upper():
        code = ord(ch)
        if 0x20 <= code <= 0x5F:
            out.append(ch)
    return "".join(out)


def fetch_book(book: str) -> dict:
    with urllib.request.urlopen(BASE_URL.format(book=book), timeout=30) as rsp:
        return json.load(rsp)


def collect(count: int) -> list[tuple[str, str]]:
    verses: list[tuple[str, str]] = []
    for book_file, display, chapters in SELECTION:
        if len(verses) >= count:
            break
        data = fetch_book(book_file)
        by_number = {int(c["chapter"]): c["verses"] for c in data["chapters"]}
        pick = chapters if chapters is not None else sorted(by_number)
        for chapter in pick:
            if len(verses) >= count:
                break
            for entry in by_number.get(chapter, []):
                if len(verses) >= count:
                    break
                text = sanitize(entry["text"])
                if not text or len(text) > 320:
                    continue
                ref = f"{display} {chapter}:{entry['verse']}"
                verses.append((ref, text))
    return verses


def emit(verses: list[tuple[str, str]], out_path: Path) -> None:
    lines = [
        "// Auto-generated by tools/make_verses.py - do not edit by hand.",
        "// Text: King James Version (public domain).",
        "#ifndef VERSES_H",
        "#define VERSES_H",
        "",
        f"#define VERSE_DB_COUNT {len(verses)}",
        "",
        "static const char *const VERSE_REFS[VERSE_DB_COUNT] = {",
    ]
    for ref, _ in verses:
        lines.append(f'    "{ref}",')
    lines.append("};")
    lines.append("")
    lines.append("static const char *const VERSE_TEXTS[VERSE_DB_COUNT] = {")
    for _, text in verses:
        escaped = text.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",')
    lines.append("};")
    lines.append("")
    lines.append("#endif // VERSES_H")
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=1024)
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent.parent / "pico_firmware_c" / "verses.h"),
    )
    args = parser.parse_args()
    verses = collect(args.count)
    emit(verses, Path(args.out))
    total_bytes = sum(len(r) + len(t) + 2 for r, t in verses)
    print(f"wrote {len(verses)} verses ({total_bytes / 1024:.1f} KiB of text) to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
